"""init2

Revision ID: 5d01d1cb736f
Revises: 413d05c4c42e
Create Date: 2025-03-20 08:42:07.588030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d01d1cb736f'
down_revision = '413d05c4c42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kalendorius',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('aprasas', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('uzduotys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pavadinimas', sa.String(length=80), nullable=True),
    sa.Column('data_nuo', sa.DateTime(timezone=50), nullable=False),
    sa.Column('data_iki', sa.DateTime(timezone=50), nullable=False),
    sa.Column('aprasymas', sa.String(length=50), nullable=False),
    sa.Column('modulis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modulis_id'], ['moduliai.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tvarkarasciai',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('savaites_diena', sa.Integer(), nullable=False),
    sa.Column('pakaitos_pavadinimas', sa.String(length=50), nullable=False),
    sa.Column('laikas_nuo', sa.Time(), nullable=False),
    sa.Column('laikas_iki', sa.Time(), nullable=False),
    sa.Column('uzduotis_id', sa.Time(), nullable=True),
    sa.Column('atsiskaitymas_id', sa.Time(), nullable=True),
    sa.Column('modulis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atsiskaitymas_id'], ['atsiskaitymai.id'], ),
    sa.ForeignKeyConstraint(['modulis_id'], ['moduliai.id'], ),
    sa.ForeignKeyConstraint(['uzduotis_id'], ['uzduotys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tvarkarasciai')
    op.drop_table('uzduotys')
    op.drop_table('kalendorius')
    # ### end Alembic commands ###
