"""vartotojo pav

Revision ID: 56d09ac4593d
Revises: a65432f146b5
Create Date: 2025-03-19 08:08:59.584916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d09ac4593d'
down_revision = 'a65432f146b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vartotojai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paveiksleliai', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vartotojai', schema=None) as batch_op:
        batch_op.drop_column('paveiksleliai')

    # ### end Alembic commands ###
