"""empty message

Revision ID: 4f3baa3488f3
Revises: b45ad0afdc70
Create Date: 2025-03-21 08:20:52.413727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3baa3488f3'
down_revision = 'b45ad0afdc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vartotojai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nesekmingi_bandymai', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blokavimo_laikas', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vartotojai', schema=None) as batch_op:
        batch_op.drop_column('blokavimo_laikas')
        batch_op.drop_column('nesekmingi_bandymai')

    # ### end Alembic commands ###
