"""empty message

Revision ID: 07ed44630fa9
Revises: 5c0121677ba4
Create Date: 2025-03-25 14:02:17.530066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07ed44630fa9'
down_revision = '5c0121677ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atsiskaitymai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atsiskaitymai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
