"""empty message

Revision ID: 341208dabc3a
Revises: 46c34e456db6
Create Date: 2025-03-25 16:31:35.563199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '341208dabc3a'
down_revision = '46c34e456db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializacijos', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('specializacijos')
    with op.batch_alter_table('studiju_programos', schema=None) as batch_op:
        batch_op.drop_constraint('studiju_programos_ibfk_1', type_='foreignkey')
        batch_op.drop_column('specializacija_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studiju_programos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specializacija_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('studiju_programos_ibfk_1', 'specializacijos', ['specializacija_id'], ['id'])

    op.create_table('specializacijos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pavadinimas', mysql.VARCHAR(collation='utf8_lithuanian_ci', length=50), nullable=False),
    sa.Column('fakultetas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fakultetas_id'], ['fakultetai.id'], name='specializacijos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_lithuanian_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('specializacijos', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    # ### end Alembic commands ###
