"""init

Revision ID: 413d05c4c42e
Revises: 
Create Date: 2025-03-20 08:39:40.831046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '413d05c4c42e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_OLD')
    with op.batch_alter_table('moduliai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('egzaminas_data', sa.DateTime(timezone=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moduliai', schema=None) as batch_op:
        batch_op.drop_column('egzaminas_data')

    op.create_table('alembic_version_OLD',
    sa.Column('version_num', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
