"""empty message

Revision ID: 46c34e456db6
Revises: ee383edc5dae
Create Date: 2025-03-25 14:39:28.297596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46c34e456db6'
down_revision = 'ee383edc5dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atsiskaitymai', schema=None) as batch_op:
        batch_op.alter_column('aprasymas',
               existing_type=mysql.VARCHAR(collation='utf8_lithuanian_ci', length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atsiskaitymai', schema=None) as batch_op:
        batch_op.alter_column('aprasymas',
               existing_type=mysql.VARCHAR(collation='utf8_lithuanian_ci', length=500),
               nullable=False)

    # ### end Alembic commands ###
