"""empty message

Revision ID: ee383edc5dae
Revises: 07ed44630fa9
Create Date: 2025-03-25 14:20:39.998952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee383edc5dae'
down_revision = '07ed44630fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atsiskaitymai', schema=None) as batch_op:
        batch_op.alter_column('data_nuo',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('data_iki',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atsiskaitymai', schema=None) as batch_op:
        batch_op.alter_column('data_iki',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('data_nuo',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
